apiVersion: network.azure.upbound.io/v1beta1
kind: VirtualNetwork
metadata:
  name: vm-sdc-001-vnet
  namespace: default
  labels:
    platform.demo/request: create-vm
spec:
  forProvider:
    addressSpace:
      - 10.20.0.0/16
    location: swedencentral
    resourceGroupName: rg-vm-sdc-001
    tags:
      COST: T3
  providerConfigRef:
    name: default
