apiVersion: network.azure.upbound.io/v1beta1
kind: NetworkInterface
metadata:
  name: vm-sdc-001-nic
  namespace: default
  labels:
    platform.demo/request: create-vm
    platform.demo/component: vm-sdc-001-nic
spec:
  forProvider:
    ipConfiguration:
      - name: ipconfig1
        privateIpAddressAllocation: Dynamic
        publicIpAddressIdSelector:
          matchLabels:
            platform.demo/request: create-vm
            platform.demo/component: vm-sdc-001-pip
        subnetIdSelector:
          matchLabels:
            platform.demo/request: create-vm
            platform.demo/component: vm-sdc-001-subnet
    location: swedencentral
    resourceGroupName: rg-vm-sdc-001
  providerConfigRef:
    name: default
