apiVersion: kubernetes.example.com/v1alpha1
kind: VMClaim
metadata:
  name: vm-sdc-001
  annotations:
    crossplane.io/external-name: vm-sdc-001
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  location: swedencentral
  resourceGroupName: rg_powerappslogs_sdc_sandbox
  adminUsername: azureuser
  sshPublicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCZUQxeOFgqd2ZXWm7PiuPagM/rw4bMErrQRBXGNcLzwV02hLXl/XUF4qAKS1Cpb5gTsmuv+YLrw+y78K72U5ZvKTLZwnqxiAH1i/OlC92UCM/sPz/yzoSg8swsOkCmzyTbGnEsxCCQDqR6iY9ZjqdMb6FGVYh9hqS/+oezUTWLvPt8tB1OReoOsuakPbcAJ7Wx4ZhV6uh0t6Ln+uBAjLW+fQKqfI0Z40Ebfi8bzFqOzogsW0BpTYMeqwD0hzW0QUregqmUHle7b7D6ND+cWptotqEpA/tSFu9hQIAOfeGuKHddbBJhSC3HGxMYTIQElu5+KNGZ8WGy2x+7IN/uHBFJMYTiiBX1cus18RFBgPa5gy1ZSn9QwS2FYCTwcqQ0NrVftWkxfl3ZrHjZxUilZwF8yVELJe92CcEnQgQl9mkdt06jWYLKtZ/6vKmGQiETbWt7F3V6nTNpT/S8LxRPkkH1XqzpQqrLeeYfTZpWex9hT2yyL7wzHRod+iiWg4GNUM7z+IshHrMxH0BG5LAAYqKP4nDQUAr+WdF8gv23ZU5IsITeMu6rII0L1lFSWCdE0ZGuUmVvbxvUgTj01ETMqst6m3mySD821jBp4hySvWViGmU2m+d6d/1HCnSbFmMvM2NVrv7Iwus6oe+h56v3E248Odtni1znettODmThbjDOiQ== vm-access
  vmSize: Standard_B2s
  image:
    publisher: Canonical
    offer: 0001-com-ubuntu-server-jammy
    sku: 22_04-lts
    version: latest
  osDisk:
    storageAccountType: Standard_LRS
    diskSizeGb: 30
  network:
    vnetAddressSpace:
      - 10.20.0.0/16
    subnetPrefix: 10.20.1.0/24
    privateIpAddressAllocation: Dynamic
    publicIpAllocationMethod: Static
  tags:
    COST: T3
    request: create-vm
