apiVersion: apimanagement.azure.com/v1api20220801
kind: Service
metadata:
  name: apim-service
  namespace: default
spec:
  azureName: apim-dev-change-me-001
  publisherEmail: apim-owner@example.com
  publisherName: APIM Dev Owner
  tags:
    environment: dev
