apiVersion: apimanagement.azure.upbound.io/v1beta1
kind: Management
metadata:
  name: apim-service
  namespace: default
  annotations:
    crossplane.io/external-name: apim-dev-change-me-001
spec:
  forProvider:
    publisherEmail: apim-owner@example.com
    publisherName: APIM Dev Owner
    tags:
      environment: dev
