apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-aks1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/gabimirea/aks-platform-engineering.git
    targetRevision: main
    path: gitops/clusters/crossplane/aks1
  destination:
    server: https://kubernetes.default.svc
    namespace: workload
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
