apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-cnpg-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/gabimirea/aks-platform-engineering.git
    targetRevision: main
    path: gitops/apps/myapp
    directory:
      include: "{AKS1-CNPG-Operator-ArgoApp.yaml,AKS1-CNPG-Demo-ArgoApp.yaml,AKSStoreDemoArgoApp.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
