apiVersion: apimanagement.azure.upbound.io/v1beta1
kind: Policy
metadata:
  name: apim-service-policy
  namespace: default
spec:
  forProvider:
    apiManagementIdSelector:
      matchLabels:
        platform.demo/component: apim-management
    xmlContent: |
      <policies>
        <inbound />
        <backend>
          <forward-request />
        </backend>
        <outbound />
        <on-error />
      </policies>
  providerConfigRef:
    name: default
