apiVersion: apimanagement.azure.upbound.io/v1beta1
kind: Product
metadata:
  name: aks-store-product
  namespace: default
spec:
  forProvider:
    apiManagementName: apim-service
    displayName: AKS Store Product
    productId: aks-store-product
    published: true
    resourceGroupName: apim-rg
    subscriptionRequired: true
  providerConfigRef:
    name: default
