apiVersion: apimanagement.azure.upbound.io/v1beta1
kind: ProductAPI
metadata:
  name: aks-store-product-api
  namespace: default
spec:
  forProvider:
    apiManagementName: apim-service
    apiName: aks-store-api
    productId: aks-store-product
    resourceGroupName: apim-rg
  providerConfigRef:
    name: default
