apiVersion: apimanagement.azure.upbound.io/v1beta1
kind: Management
metadata:
  name: apim-service
  namespace: default
  labels:
    platform.demo/component: apim-management
spec:
  forProvider:
    location: swedencentral
    publisherEmail: platform-team@example.com
    publisherName: Platform Team
    resourceGroupName: apim-rg
    skuName: Developer_1
    tags:
      managed-by: gitops
      workload: apim
  providerConfigRef:
    name: default
