apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: apim-rg
  namespace: default
spec:
  forProvider:
    name: apim-rg
    location: swedencentral
  providerConfigRef:
    name: default
