apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: ${{ values.resourceGroupName }}
  namespace: ${{ values.kubernetesNamespace }}
  labels:
    platform.demo/request: ${{ values.requestName }}
spec:
  forProvider:
    location: ${{ values.location }}
    tags:
      COST: ${{ values.costTag }}
  providerConfigRef:
    name: ${{ values.providerConfigName }}
