apiVersion: network.azure.upbound.io/v1beta1
kind: VirtualNetwork
metadata:
  name: ${{ values.vmName }}-vnet
  namespace: ${{ values.kubernetesNamespace }}
  labels:
    platform.demo/request: ${{ values.requestName }}
spec:
  forProvider:
    addressSpace:
      - 10.20.0.0/16
    location: ${{ values.location }}
    resourceGroupName: ${{ values.resourceGroupName }}
    tags:
      COST: ${{ values.costTag }}
  providerConfigRef:
    name: ${{ values.providerConfigName }}
