apiVersion: network.azure.upbound.io/v1beta1
kind: Subnet
metadata:
  name: ${{ values.vmName }}-subnet
  namespace: ${{ values.kubernetesNamespace }}
  labels:
    platform.demo/request: ${{ values.requestName }}
    platform.demo/component: ${{ values.vmName }}-subnet
spec:
  forProvider:
    addressPrefixes:
      - 10.20.1.0/24
    resourceGroupName: ${{ values.resourceGroupName }}
    virtualNetworkName: ${{ values.vmName }}-vnet
  providerConfigRef:
    name: ${{ values.providerConfigName }}
