apiVersion: network.azure.com/v1api20201101
kind: PublicIPAddress
metadata:
  name: ${{ values.vmName }}-pip
  namespace: ${{ values.kubernetesNamespace }}
  labels:
    platform.demo/request: ${{ values.requestName }}
spec:
  location: ${{ values.location }}
  owner:
    name: ${{ values.resourceGroupName }}
  sku:
    name: Standard
  publicIPAllocationMethod: Static
