apiVersion: network.azure.upbound.io/v1beta1
kind: PublicIP
metadata:
  name: ${{ values.vmName }}-pip
  namespace: ${{ values.kubernetesNamespace }}
  labels:
    platform.demo/request: ${{ values.requestName }}
    platform.demo/component: ${{ values.vmName }}-pip
spec:
  forProvider:
    allocationMethod: Static
    location: ${{ values.location }}
    resourceGroupName: ${{ values.resourceGroupName }}
    sku: Standard
    tags:
      COST: ${{ values.costTag }}
  providerConfigRef:
    name: ${{ values.providerConfigName }}
