apiVersion: network.azure.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  name: ${{ values.vmName }}-nsg
  namespace: ${{ values.kubernetesNamespace }}
  labels:
    platform.demo/request: ${{ values.requestName }}
    platform.demo/component: ${{ values.vmName }}-nsg
spec:
  forProvider:
    location: ${{ values.location }}
    resourceGroupName: ${{ values.resourceGroupName }}
    tags:
      COST: ${{ values.costTag }}
  providerConfigRef:
    name: ${{ values.providerConfigName }}
