apiVersion: network.azure.upbound.io/v1beta1
kind: SecurityRule
metadata:
  name: ${{ values.vmName }}-nsg-allow-ssh
  namespace: ${{ values.kubernetesNamespace }}
  labels:
    platform.demo/request: ${{ values.requestName }}
spec:
  forProvider:
    access: Allow
    description: Allow SSH from any source (demo only).
    destinationAddressPrefix: "*"
    destinationPortRange: "22"
    direction: Inbound
    networkSecurityGroupName: ${{ values.vmName }}-nsg
    priority: 101
    protocol: Tcp
    resourceGroupName: ${{ values.resourceGroupName }}
    sourceAddressPrefix: "*"
    sourcePortRange: "*"
  providerConfigRef:
    name: ${{ values.providerConfigName }}
