apiVersion: network.azure.upbound.io/v1beta1
kind: NetworkInterface
metadata:
  name: ${{ values.vmName }}-nic
  namespace: ${{ values.kubernetesNamespace }}
  labels:
    platform.demo/request: ${{ values.requestName }}
    platform.demo/component: ${{ values.vmName }}-nic
spec:
  forProvider:
    ipConfiguration:
      - name: ipconfig1
        privateIpAddressAllocation: Dynamic
        publicIpAddressIdSelector:
          matchLabels:
            platform.demo/request: ${{ values.requestName }}
            platform.demo/component: ${{ values.vmName }}-pip
        subnetIdSelector:
          matchLabels:
            platform.demo/request: ${{ values.requestName }}
            platform.demo/component: ${{ values.vmName }}-subnet
    location: ${{ values.location }}
    resourceGroupName: ${{ values.resourceGroupName }}
  providerConfigRef:
    name: ${{ values.providerConfigName }}
