apiVersion: v1
kind: Secret
metadata:
  name: ${{ values.vmName }}-admin-password
  namespace: ${{ values.kubernetesNamespace }}
  labels:
    platform.demo/request: ${{ values.requestName }}
type: Opaque
stringData:
  password: ${{ values.vmAdminPassword }}
