apiVersion: compute.azure.upbound.io/v1beta1
kind: LinuxVirtualMachine
metadata:
  name: ${{ values.vmName }}
  namespace: ${{ values.kubernetesNamespace }}
  labels:
    platform.demo/request: ${{ values.requestName }}
spec:
  forProvider:
    adminPasswordSecretRef:
      name: ${{ values.vmName }}-admin-password
      key: password
      namespace: ${{ values.kubernetesNamespace }}
    adminUsername: ${{ values.vmAdminUsername }}
    disablePasswordAuthentication: false
    location: ${{ values.location }}
    networkInterfaceIdsRefs:
      - name: ${{ values.vmName }}-nic
    osDisk:
      - caching: ReadWrite
        storageAccountType: Standard_LRS
    resourceGroupName: ${{ values.resourceGroupName }}
    size: ${{ values.vmSize }}
    sourceImageReference:
      - publisher: Canonical
        offer: 0001-com-ubuntu-server-jammy
        sku: 22_04-lts
        version: latest
  providerConfigRef:
    name: ${{ values.providerConfigName }}
