apiVersion: storage.azure.upbound.io/v1beta1
kind: Account
metadata:
  name: ${{ values.requestName }}-sa
  namespace: ${{ values.kubernetesNamespace }}
  labels:
    platform.demo/request: ${{ values.requestName }}
  annotations:
    crossplane.io/external-name: ${{ values.storageAccountName }}
spec:
  forProvider:
    accountReplicationType: ${{ values.storageReplicationType }}
    accountTier: ${{ values.storageAccountTier }}
    location: ${{ values.location }}
    resourceGroupName: ${{ values.resourceGroupName }}
    tags:
      COST: ${{ values.costTag }}
  providerConfigRef:
    name: ${{ values.providerConfigName }}
