apiVersion: network.azure.com/v1api20201101
kind: VirtualNetworksSubnet
metadata:
  name: vm-sdc-001-subnet
  namespace: default
  labels:
    platform.demo/request: create-vm
spec:
  owner:
    name: vm-sdc-001-vnet
  addressPrefix: 10.20.1.0/24
