apiVersion: network.azure.com/v1api20201101
kind: NetworkSecurityGroup
metadata:
  name: vm-sdc-001-nsg
  namespace: default
  labels:
    platform.demo/request: create-vm
spec:
  location: swedencentral
  owner:
    name: rg-vm-demo-001
