apiVersion: network.azure.upbound.io/v1beta1
kind: SecurityRule
metadata:
  name: vm-sdc-001-nsg-allow-ssh
  namespace: default
  labels:
    platform.demo/request: create-vm
spec:
  forProvider:
    access: Allow
    description: Allow SSH from any source (demo only).
    destinationAddressPrefix: "*"
    destinationPortRange: "22"
    direction: Inbound
    networkSecurityGroupName: vm-sdc-001-nsg
    priority: 101
    protocol: Tcp
    resourceGroupName: rg-vm-sdc-001
    sourceAddressPrefix: "*"
    sourcePortRange: "*"
  providerConfigRef:
    name: default
