apiVersion: network.azure.com/v1api20201101
kind: NetworkInterface
metadata:
  name: vm-sdc-001-nic
  namespace: default
  labels:
    platform.demo/request: create-vm
spec:
  location: swedencentral
  owner:
    name: rg-vm-demo-001
  networkSecurityGroup:
    reference:
      group: network.azure.com
      kind: NetworkSecurityGroup
      name: vm-sdc-001-nsg
  ipConfigurations:
    - name: ipconfig1
      privateIPAllocationMethod: Dynamic
      publicIPAddress:
        reference:
          group: network.azure.com
          kind: PublicIPAddress
          name: vm-sdc-001-pip
      subnet:
        reference:
          group: network.azure.com
          kind: VirtualNetworksSubnet
          name: vm-sdc-001-subnet
