apiVersion: v1
kind: Secret
metadata:
  name: vm-sdc-001-admin-password
  namespace: default
  labels:
    platform.demo/request: create-vm
type: Opaque
stringData:
  password: |-
    ***************
