apiVersion: compute.azure.com/v1api20201201
kind: VirtualMachine
metadata:
  name: vm-sdc-001
  namespace: default
  labels:
    platform.demo/request: create-vm
spec:
  location: swedencentral
  owner:
    name: rg-vm-demo-001
  hardwareProfile:
    vmSize: Standard_B2s
  networkProfile:
    networkInterfaces:
      - reference:
          group: network.azure.com
          kind: NetworkInterface
          name: vm-sdc-001-nic
  osProfile:
    computerName: vm-sdc-001
    adminUsername: azureuser
    adminPassword:
      name: vm-sdc-001-admin-password
      key: password
  storageProfile:
    imageReference:
      publisher: Canonical
      offer: 0001-com-ubuntu-server-jammy
      sku: 22_04-lts
      version: latest
