provider:
  enabled: true
  metadata:
    annotations: {}
    labels:
      app.kubernetes.io/managed-by: Helm
      azure.workload.identity/use: "true"
  package:
    registry: xpkg.upbound.io/upbound
    version: v2.3.1

providerConfig:
  enabled: false

providers:
  - containerservice
  - compute
  - storage
  - network
  - resources
  - authorization

deploymentRuntimeConfig:
  enabled: true
