apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aks0-cnpg-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/gabimirea/aks-platform-engineering.git
    targetRevision: main
    path: gitops/apps/myapp/postgres/overlays/demo
  destination:
    name: aks0
    namespace: cnpg-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
