apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aks0-aks-store-demo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Azure-Samples/aks-store-demo.git
    targetRevision: HEAD
    path: kustomize/overlays/dev

  destination:
    name: aks0
    namespace: pets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
