apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aks-store-demo
  namespace: argocd
spec:
  project: default
  source:    
      repoURL: https://github.com/Azure-Samples/aks-store-demo.git
      targetRevision: HEAD
      path: kustomize/overlays/dev             
  syncPolicy:
      automated: {}
      syncOptions:
      - CreateNamespace=true
  destination:
      namespace: store-demo
      name: aks0 