apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aks0-aks-store-demo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/gabimirea/aks-platform-engineering.git
    targetRevision: main
    path: gitops/apps/myapp/aks-store-demo-overlay

  destination:
    name: aks0
    namespace: pets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
